pipeline {
  agent any
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('Build') { steps { sh 'mvn clean package -DskipTests' } }
    stage('Test') { steps { sh 'mvn test' } }
    stage('Sonar') { steps { echo 'Run sonar: configure sonar credentials in Jenkins & uncomment mvn sonar:sonar' } }
    stage('Publish') { steps { echo 'Publish to Nexus: configure credentials & run mvn deploy' } }
  }
  post {
    always { archiveArtifacts artifacts: 'target/*.war', fingerprint: true }
  }
}
